require("MG.options")
require("MG.keymaps")
require("MG.plugins")
require("MG.colorscheme")
require("MG.alpha")
require("MG.autocommands")
require("MG.whichkey")
require("MG.lualine")
require("MG.code_runner")
require("MG.toggleterm")
require("MG.cmp")
require("MG.lsp")
require("MG.telescope")
require("MG.treesitter")
require("MG.gitsigns")
require("MG.autopairs")
require("MG.comment")
require("MG.bufferline")
require("MG.project")
require("MG.nvim-tree")
require("MG.web-dev.colorizer")
require("MG.web-dev.emmet")
require("MG.mason")

-- require "user.impatient"
-- require "user.indentline"
